name: dart_state_chart
description: Model state machines and state charts in dart and flutter
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.2
  test: ^1.24.0
  equatable: ^2.0.5
