name: flutter_machine
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  dart_state_chart:
    path: ../core
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
